# Copyright 2016 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name = 'colors',
  sources = ['colors.py']
)

python_library(
  name = 'console',
  sources = ['console.py'],
  dependencies = ['3rdparty/python:blessed']
)
