# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

source_root('examples/3rdparty/js', npm_remote_module)
source_root('examples/src/js', npm_module)
source_root('src/python', python_library)
source_root('tests/python', python_library, python_tests)
