# Copyright 2016 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_binary(
  name='engine_console_demo',
  source='engine_console_demo.py',
  dependencies=['src/python/pants/ui:console']
)
