npm_module(
  name='client',
  version='0.0.1',
  main='main.jsx',
  dependencies=[':client'],
  description='''
An example module to illustrate the usage of a package.json. pants uses the package.json
in the same directory as a npm_module, and fills in the name and dependencies fields for
a module during the build process.
''',
)
