# Copyright 2016 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  name='engine',
  sources=['test_engine.py'],
  coverage=['pants.engine'],
  dependencies=[
    'src/python/pants/ui:engine',
  ]
)
