# Copyright 2016 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  name='colors',
  sources=['test_colors.py'],
  coverage=['pants.ui.colors'],
  dependencies=[
    'src/python/pants/ui:colors',
  ]
)

python_tests(
  name='engine',
  sources=['test_engine.py'],
  coverage=['pants.ui.engine'],
  dependencies=[
    'src/python/pants/ui:engine',
  ]
)
